allowBuilds:
  esbuild: true

blockExoticSubdeps: true
dedupePeers: true
dedupePeerDependents: true
minimumReleaseAge: 10080
shellEmulator: true

# temporarily disable for now until we migrate away from jest and tsup
# trustPolicy: no-downgrade

